site_name: Backend Notes
site_url: https://kapustnyak.github.io/backend_notes/
repo_url: https://github.com/kapustnyak/backend_notes
repo_name: kapustnyak/backend_notes

docs_dir: "."
use_directory_urls: true

theme:
  name: material
  language: ru

plugins:
  - search
  - roamlinks
  - awesome-pages
  - glightbox

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
