{\rtf1\ansi\ansicpg1251\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs24 \cf0 site_name: Backend Notes\
site_url: https://kapustnyak.github.io/backend_notes/\
repo_url: https://github.com/kapustnyak/backend_notes\
repo_name: kapustnyak/backend_notes\
\
docs_dir: "."\
use_directory_urls: true\
\
theme:\
  name: material\
  language: ru\
\
plugins:\
  - search\
  - roamlinks\
  - awesome-pages\
  - glightbox\
\
markdown_extensions:\
  - admonition\
  - footnotes\
  - attr_list\
  - def_list\
  - toc:\
      permalink: true\
  - pymdownx.superfences\
  - pymdownx.details\
  - pymdownx.caret\
  - pymdownx.mark\
  - pymdownx.tilde}